sudo: false
language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release
