sudo: false
language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
script:
  npm run build
after_success:
  npm run semantic-release
